# Amazon Reviews 2014 
# ==========================================


category: Sports_and_Outdoors
metadata: sentence  
split: leave_one_out  # leave_one_out


sent_emb_model: text-embedding-3-large
sent_emb_dim: 3072
sent_emb_pca: 1280
openai_api_key: sk-WR6aJpZ81gACet0aN8wXYx0lUfC0WgjjcrFRZAJKatkeuTke
openai_base_url: https://yunwu.ai/v1


sent_emb_batch_size: 100
n_codebook: 32
codebook_size: 256
faiss_omp_num_threads: 16
opq_use_gpu: false
opq_gpu_id: 0